#! /usr/bin/env python3

# Fully delete an S3 bucket, even if it has versioned objects

# Usage: ./delete_bucket bucket_name

import sys
import boto3
import os

try:
    bucket_name = sys.argv[1]
except IndexError:
    print(f"Usage: {sys.argv[0]} bucket_name")
    exit(1)

bucket_name = bucket_name.removeprefix("s3://")
account_id = boto3.client("sts").get_caller_identity().get("Account")

# Make sure the user is deleting the bucket they intended to
print()
print("AWS_PROFILE = " + os.environ.get("AWS_PROFILE", "Not Set"))
print("Account ID  = " + account_id)
print("Bucket      = s3://" + bucket_name)
print()
print("Press Enter to DELETE the above bucket and all its contents.")
input("Press Ctrl-C to cancel.")

# Carry out the actions
bucket = boto3.resource("s3").Bucket(bucket_name)
bucket.object_versions.all().delete()
bucket.delete()
print("All operations completed successfully")
