#! /usr/bin/env python3

# Fully delete an S3 bucket, even if it has versioned objects

import sys
import boto3
import os

try:
    bucket_name = sys.argv[1]
except IndexError:
    print("Specify a bucket name")
    exit(1)

print("This bucket will be deleted: s3://" + bucket_name)
print("AWS_PROFILE = " + os.environ['AWS_PROFILE'])
input("Press enter to continue or Ctrl-C to cancel")

s3 = boto3.resource('s3')
bucket = s3.Bucket(bucket_name)
bucket.object_versions.all().delete()
bucket.delete()
