#!/usr/bin/env python3

import sys
import boto3
import os


def delete_iam_role(role_name):
    iam_client = boto3.client("iam")

    try:
        print(f"Deleting inline policies for role: {role_name}")
        inline_policies = iam_client.list_role_policies(RoleName=role_name)[
            "PolicyNames"
        ]
        for policy_name in inline_policies:
            print(f"Deleting inline policy: {policy_name}")
            iam_client.delete_role_policy(RoleName=role_name, PolicyName=policy_name)

        print(f"Detaching managed policies for role: {role_name}")
        attached_policies = iam_client.list_attached_role_policies(RoleName=role_name)[
            "AttachedPolicies"
        ]
        for policy in attached_policies:
            policy_arn = policy["PolicyArn"]
            print(f"Detaching managed policy: {policy_arn}")
            iam_client.detach_role_policy(RoleName=role_name, PolicyArn=policy_arn)

        print(f"Removing role from instance profiles for role: {role_name}")
        instance_profiles = iam_client.list_instance_profiles_for_role(
            RoleName=role_name
        )["InstanceProfiles"]
        for profile in instance_profiles:
            profile_name = profile["InstanceProfileName"]
            print(f"Removing role from instance profile: {profile_name}")
            iam_client.remove_role_from_instance_profile(
                RoleName=role_name, InstanceProfileName=profile_name
            )

        print(f"Deleting role: {role_name}")
        iam_client.delete_role(RoleName=role_name)
        print(f"Role {role_name} deleted successfully.")

    except iam_client.exceptions.NoSuchEntityException:
        print(f"Role {role_name} does not exist.")
    except Exception as e:
        print(f"An error occurred: {str(e)}")


if __name__ == "__main__":
    try:
        role_name = sys.argv[1]
    except IndexError:
        print("Specify a role name")
        sys.exit(1)

    aws_profile = os.getenv("AWS_PROFILE", "default")
    print(f"This role will be deleted: {role_name}")
    print(f"AWS_PROFILE = {aws_profile}")
    input("Press Enter to continue or Ctrl-C to cancel")

    delete_iam_role(role_name)
